repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      # Pre-commit (on commit) - auto-fix
      - id: ruff
        args: ["--fix"]
        files: ^(src/|tests/|tools/).*\.py$
        exclude: ^(prototypes/|examples/)
        stages: [pre-commit]
      - id: ruff-format
        files: ^(src/|tests/|tools/).*\.py$
        exclude: ^(prototypes/|examples/)
        stages: [pre-commit]

      # Pre-push (on push) - check only, no fixes
      - id: ruff
        name: ruff (pre-push, check-only)
        args: ["--no-fix"]
        files: ^(src/|tests/|tools/).*\.py$
        exclude: ^(prototypes/|examples/)
        stages: [pre-push]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      # Pre-commit (on commit) - auto format
      - id: black
        files: ^(src/|tests/|tools/).*\.py$
        exclude: ^(prototypes/|examples/)
        stages: [pre-commit]

      # Pre-push (on push) - check only
      - id: black
        name: black (pre-push, check)
        args: ["--check"]
        files: ^(src/|tests/|tools/).*\.py$
        exclude: ^(prototypes/|examples/)
        stages: [pre-push]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      # Pre-commit (on commit) - auto sort
      - id: isort
        args: ["--profile=black"]
        files: ^(src/|tests/|tools/).*\.py$
        exclude: ^(prototypes/|examples/)
        stages: [pre-commit]

      # Pre-push (on push) - check only
      - id: isort
        name: isort (pre-push, check)
        args: ["--profile=black", "--check-only"]
        files: ^(src/|tests/|tools/).*\.py$
        exclude: ^(prototypes/|examples/)
        stages: [pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      # Pre-commit (on commit) - optional, skip by default
      - id: mypy
        additional_dependencies: [types-PyYAML>=6.0.0, types-requests>=2.31.0, pandas-stubs]
        files: ^(src/|tests/).*\.py$
        exclude: ^prototypes/
        args: ["--ignore-missing-imports"]
        stages: [pre-commit]

      # Pre-push (on push) - enforce typing
      - id: mypy
        name: mypy (pre-push)
        additional_dependencies: [types-PyYAML>=6.0.0, types-requests>=2.31.0, pandas-stubs]
        files: ^(src/|tests/).*\.py$
        exclude: ^prototypes/
        args: ["--ignore-missing-imports"]
        stages: [pre-push]



