site_name: Mancer Framework
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - versioning
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Concepts: concepts.md
  - Architecture:
      - Overview: architecture/overview.md
      - Modules: architecture/modules.md
      - Command Flow: architecture/command-flow.md
  - User Guide:
      - Commands: user-guide/commands.md
      - Configuration: user-guide/configuration.md
      - Examples: user-guide/examples.md
  - API Reference: api.md
  - Extending Mancer:
      - Custom Commands: extending/custom-commands.md
      - Backends: extending/backends.md
      - Plugins: extending/plugins.md
  - Development: development.md
  - Versioning: versioning.md
  - FAQ: faq.md
  - Contact: contact.md
