site_name: Mancer Framework
theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - versioning

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            merge_init_into_class: true
            docstring_style: google
            docstring_section_style: list

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Concepts: concepts.md
  - Architecture:
      - Overview: architecture/overview.md
      - Modules: architecture/modules.md
      - Command Flow: architecture/command-flow.md
  - User Guide:
      - Commands: user-guide/commands.md
      - Configuration: user-guide/configuration.md
      - Data & Formatting: user-guide/data-formatting.md
      - Logging & Errors: user-guide/logging-and-errors.md
      - Versioning & Compatibility: user-guide/versioning-compatibility.md
  - Examples:
      - Quick Examples: user-guide/examples.md
      - All Examples: examples/all-examples.md
  - API Reference:
      - Overview: api.md
      - Application: api/application.md
      - Domain: api/domain.md
      - Infrastructure: api/infrastructure.md
  - Extending Mancer:
      - Custom Commands: extending/custom-commands.md
      - Backends: extending/backends.md
      - Plugins: extending/plugins.md
  - Development: development.md
  - Testing: development/testing-overview.md
  - Versioning: versioning.md
  - FAQ: faq.md
  - Contact: contact.md
