tools:
  # GNU Coreutils
  ls:
    - "8.30"
    - "8.31"
    - "8.32"
    - "9.0"
    - "9.1"
  cat:
    - "8.30"
    - "8.31"
    - "8.32"
    - "9.0"
    - "9.1"
  echo:
    - "8.30"
    - "8.31"
    - "8.32"
    - "9.0"
    - "9.1"
  find:
    - "4.7.0"
    - "4.8.0"
    - "4.9.0"
  
  # GNU Grep
  grep:
    - "3.1"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
  
  # Procps-ng
  ps:
    - "3.3.15"
    - "3.3.16"
    - "3.3.17"
  
  # Util-linux
  df:
    - "2.34"
    - "2.35"
    - "2.36"
    - "2.37"
    - "2.38"
  
  # Systemd
  systemctl:
    - "239"
    - "245"
    - "247"
    - "249"
    - "250"
    - "251"
    - "252"
  
  # Hostname
  hostname:
    - "3.21"
    - "3.22"
    - "3.23"
  
  # wc
  wc:
    - "8.30"
    - "8.31"
    - "8.32"
    - "9.0"
    - "9.1" 