version: '3'

services:
  mancer-test-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TEST_USER: ${TEST_USER_1:-mancer1}
        TEST_PASSWORD: ${TEST_PASSWORD_1:-test_password1}
        TEST_UID: 1000
    container_name: mancer-test-1
    ports:
      - "${SSH_PORT_1:-2221}:22"
    volumes:
      - ../..:/home/${TEST_USER_1:-mancer1}/mancer
    environment:
      - TZ=Europe/Warsaw
    command: /usr/sbin/sshd -D
    restart: unless-stopped

  mancer-test-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TEST_USER: ${TEST_USER_2:-mancer2}
        TEST_PASSWORD: ${TEST_PASSWORD_2:-test_password2}
        TEST_UID: 1001
    container_name: mancer-test-2
    ports:
      - "${SSH_PORT_2:-2222}:22"
    volumes:
      - ../..:/home/${TEST_USER_2:-mancer2}/mancer
    environment:
      - TZ=Europe/Warsaw
    command: /usr/sbin/sshd -D
    restart: unless-stopped

  mancer-test-3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TEST_USER: ${TEST_USER_3:-mancer3}
        TEST_PASSWORD: ${TEST_PASSWORD_3:-test_password3}
        TEST_UID: 1002
    container_name: mancer-test-3
    ports:
      - "${SSH_PORT_3:-2223}:22"
    volumes:
      - ../..:/home/${TEST_USER_3:-mancer3}/mancer
    environment:
      - TZ=Europe/Warsaw
    command: /usr/sbin/sshd -D
    restart: unless-stopped

networks:
  default:
    name: mancer-test-network 