version: '3'

services:
  mancer-test-1:
    build:
      context: .
      dockerfile: machine-template/Dockerfile
      args:
        TEST_USER: ${TEST_USER_1}
        TEST_PASSWORD: ${TEST_PASSWORD_1}
        PRESET: ${PRESET_1:-none}
    container_name: mancer-test-1
    hostname: mancer-test-1
    ports:
      - "${SSH_PORT_1}:22"
    privileged: true
    stop_signal: SIGRTMIN+3
    environment:
      - container=docker
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      mancer_network:
        ipv4_address: 10.100.2.101
    restart: unless-stopped

  mancer-test-2:
    build:
      context: .
      dockerfile: machine-template/Dockerfile
      args:
        TEST_USER: ${TEST_USER_2}
        TEST_PASSWORD: ${TEST_PASSWORD_2}
        PRESET: ${PRESET_2:-none}
    container_name: mancer-test-2
    hostname: mancer-test-2
    ports:
      - "${SSH_PORT_2}:22"
    privileged: true
    stop_signal: SIGRTMIN+3
    environment:
      - container=docker
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      mancer_network:
        ipv4_address: 10.100.2.102
    restart: unless-stopped

  mancer-test-3:
    build:
      context: .
      dockerfile: machine-template/Dockerfile
      args:
        TEST_USER: ${TEST_USER_3}
        TEST_PASSWORD: ${TEST_PASSWORD_3}
        PRESET: ${PRESET_3:-none}
    container_name: mancer-test-3
    hostname: mancer-test-3
    ports:
      - "${SSH_PORT_3}:22"
    privileged: true
    stop_signal: SIGRTMIN+3
    environment:
      - container=docker
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      mancer_network:
        ipv4_address: 10.100.2.103
    restart: unless-stopped

networks:
  mancer_network:
    name: docker_test_mancer_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.2.0/24
          gateway: 10.100.2.1 