name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Publikuj przy push tagów wersji (np. v0.1.3)

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi  # Nazwa środowiska z PyPI trusted publisher
    
    permissions:
      id-token: write  # Wymagane dla trusted publishing na PyPI
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # Nie potrzebujemy tokenów - używamy trusted publisher
